spring:
  application:
    name: handshake
  
  # Database Configuration
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/handshake?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA Configuration
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true
  
  # AWS S3 Configuration
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID:your-access-key}
        secret-key: ${AWS_SECRET_ACCESS_KEY:your-secret-key}
      region:
        static: ${AWS_REGION:ap-northeast-2}
      s3:
        bucket: ${AWS_S3_BUCKET:your-bucket-name}