spring:
  application:
    name: surocksang
  
  # Database Configuration
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/surocksang?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:ssafy}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA Configuration
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true
  
  # AWS S3 Configuration
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID:your-access-key}
        secret-key: ${AWS_SECRET_ACCESS_KEY:your-secret-key}
      region:
        static: ${AWS_REGION:ap-northeast-2}
      s3:
        bucket: ${AWS_S3_BUCKET:your-bucket-name}

cors:
  allowed-origins: ${CORS:http://localhost:3000}

# SWAGGER CONFIG
swagger:
  server-url: ${SWAGGER_URL:http://localhost:8080/swagger}

logging:
  level:
    root: INFO
    org.springframework.web.cors: DEBUG  # CORS 로그 활성화
#    org.hibernate.SQL: debug       # 실행되는 SQL 문 출력
#    org.hibernate.type.descriptor.sql.BasicBinder: trace  # 바인딩되는 값 출력
#    org.hibernate.orm.jdbc.bind: trace                    # Hibernate 6.x 이상에서 바인딩 출력
#    org.hibernate.engine.jdbc.batch.internal.BatchingBatch: debug  # 배치 쿼리 로그
#    org.hibernate: info          # 전체 Hibernate 로그 레벨 (기본 INFO)

server.port: 8080